services:
  - type: web
    name: my-streamlit-app
    env: python
    plan: free
    buildCommand: sudo apt-get update && xargs -a apt-packages.txt sudo apt-get install -y && pip install -r requirements.txt
    startCommand: python -m streamlit run app.py --server.port $PORT --server.headless true
