services:
  - type: web
    name: pdf-analyst-chatbot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false   # You set this in Render Dashboard
